---
platform: linux
image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
  - name: cf-plugin-source
    path: gopath/src/github.com/anynines/cf_service_jumper_cli_plugin

run:
  path: gopath/src/github.com/anynines/cf_service_jumper_cli_plugin/bin/ci-test.sh
